### PR TITLE
add QOM PEPE

### PR DESCRIPTION
**Pull request by oranges000**

### CODE REVIEW

**Comment by RobotMasterxo** [comment]
Telegram is a must same goes for LP locked or burned.

**Comment by oranges000** [comment]
> Telegram is a must same goes for LP locked or burned.

TG Added. First LP Burn Added. @RobotMasterxo

**Comment by RobotMasterxo** [comment]
> > Telegram is a must same goes for LP locked or burned.
> 
> TG Added. First LP Burn Added. @RobotMasterxo

100% LP burn or wait for locker before whitelist

**Comment by oranges000** [comment]
> > > Telegram is a must same goes for LP locked or burned.
> > 
> > 
> > TG Added. First LP Burn Added. @RobotMasterxo
> 
> 100% LP burn or wait for locker before whitelist

@RobotMasterxo 2nd burn has occurred. 100% of LP now burned. 
https://scan.qom.one/tx/0xf2415ff77d393d1b7d839b889a799046752b23dae0f3266565f6bed7bd782009

**Pull request merged**
