### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Dakinigoddes**

### CODE REVIEW

**Comment by RobotMasterxo** [comment]
> _ No description provided. _

Fix the logo file extension

**Comment by Dakinigoddes** [comment]
logo png

**Review by Dakinigoddes — COMMENTED** [review]
logo png

**Comment by RobotMasterxo** [comment]
> logo png

its wrong , at the moment is logo.png.png and telegram.text.txt

**Comment by Dakinigoddes** [comment]
logo
[telegram.txt](https://github.com/user-attachments/files/17943321/telegram.txt)

**Pull request closed without merging**
