### PR TITLE
ADD QOMAGA

### PR DESCRIPTION
**Pull request by QOMAGA**

### CODE REVIEW

**Comment by voldin912** [comment]
I want to know the meaning of 20k.
Could you tell me if this means 100 holders should have to have at least 20k QOM or 20k USD?

**Comment by QOMAGA** [comment]
> I want to know the meaning of 20k. Could you tell me if this means 100 holders should have to have at least 20k QOM or 20k USD?

I do not understand your question ser? 

We added 512 330 976 781 WQOM worth around that time 25-27k$ to LP together with QOMAGA

LP pool is as of today 12th of june 12:34 PM UTC valued to around 92 000$ USD and is 100% burned

please clarify your question.

**Comment by voldin912** [comment]
Sorry for the confusion.
As a developer, I want to list my token to whitelist so send message for help.
Thank you for your reply.

**Comment by QOMAGA** [comment]
> Sorry for the confusion. As a developer, I want to list my token to whitelist so send message for help. Thank you for your reply.

Read the README and follow instructions

**Pull request merged**
