### PR TITLE
Create 0x6ab64A546B25108080f4a7F923015158546B5d02

### PR DESCRIPTION
**Pull request by QOMTURBO**
[telegram.txt](https://github.com/user-attachments/files/15800887/telegram.txt)
logo

### CODE REVIEW

**Comment by QOMTURBO** [comment]
Greetings ! 

LP tokens burned 100% 
Telegram Up 
1 Week old soon
155 Holders
20k Liquidity - All time high was 400% Higher , It's changing .

**Comment by RobotMasterxo** [comment]
> Greetings !
> 
> LP tokens burned 100% Telegram Up 1 Week old soon 155 Holders 20k Liquidity - All time high was 400% Higher , It's changing .

You need to upload Telegram.txt file please follow the requirements.

**Comment by QOMTURBO** [comment]
> > Greetings !
> > LP tokens burned 100% Telegram Up 1 Week old soon 155 Holders 20k Liquidity - All time high was 400% Higher , It's changing .
> 
> You need to upload Telegram.txt file please follow the requirements.

logo
[telegram.txt](https://github.com/user-attachments/files/15808523/telegram.txt)

**Comment by QOMTURBO** [comment]
It has been uploaded together with Logo

**Pull request closed without merging**
