### PR TITLE
Create 0xAC0d6D4DC3f34B489A5bC580D83884aF2A33ebad

### PR DESCRIPTION
**Pull request by qDOGSQOM**
telegram.txt
qDOGS

NAME: DOGS
SYMBOL: qDOGS
TELEGRAM: https://t.me/CawDogs
LP BURNED: 0x348d283c93e1bace9d0a08b12e7204e64ef04df41e9cee38ede5c73890f65db6

### CODE REVIEW

**Comment by RobotMasterxo** [comment]
You need to add the folder with the CA then a telegram.txt file inside and logo.png

**Comment by qDOGSQOM** [comment]
> You need to add the folder with the CA then a telegram.txt file inside and logo.png

Please send simple instructions

**Comment by qDOGSQOM** [comment]
> > You need to add the folder with the CA then a telegram.txt file inside and logo.png
> 
> Please send simple instructions

Steps on how to create and then add folder

**Comment by qDOGSQOM** [comment]
> You need to add the folder with the CA then a telegram.txt file inside and logo.png 

https://github.com/qDOGSQOM/qDOGSQOM/blob/4e57aca8ac5adbb1a9c1681c2ed56dedd2f814d2/%24qDOGS%20Official%20Contract%20Address%3A%200xAC0d6D4DC3f34B489A5bC580D83884aF2A33ebad/telegram.txt

**Comment by qDOGSQOM** [comment]
> You need to add the folder with the CA then a telegram.txt file inside and logo.png 

https://github.com/RobotMasterxo/qomswapassets/pull/36

**Pull request closed without merging**
